### ISSUE TITLE
TypeError: sequence item 0: expected str instance, numpy.int64 found

### ISSUE THREAD

**Issue by Bio-finder** [zheminzhou/pHierCC#3]
Good morning,
I have an issue when I use your tool with the example data:
After installing the tool in python 3.7 I get the following error when I run it: 

```
 pHierCC -p YERwgMLST.cgMLSTv1.profile.gz -o YERwgMLST.cgMLSTv1.HierCC

2022-04-19 10:39:51,454 | Loaded in allelic profiles with dimension: 4371 and 1554. The first column is assumed to be type id.

2022-04-19 10:39:51,455 | Start HierCC assignments

2022-04-19 10:39:51,566 | Calculate distance matrix

2022-04-19 10:40:09,869 | Start Single linkage clustering

2022-04-19 10:40:10,883 | Attach genomes onto the tree.

Traceback (most recent call last):
  File "/home/bebergk/venvs/camel_3.0_p3.7/bin/pHierCC", line 8, in <module>
    sys.exit(phierCC())

  File "/home/bebergk/venvs/camel_3.0_p3.7/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)

  File "/home/bebergk/venvs/camel_3.0_p3.7/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)

  File "/home/bebergk/venvs/camel_3.0_p3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/home/bebergk/venvs/camel_3.0_p3.7/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)

  File "/home/bebergk/venvs/camel_3.0_p3.7/lib/python3.7/site-packages/pHierCC/pHierCC.py", line 135, in phierCC
    fout.write('\t'.join([n] + [str(rr) for rr in r[1:]]) + '\n')

TypeError: sequence item 0: expected str instance, numpy.int64 found
```

Could you help me to see what is going wrong?

Also, just in case, my final objective would be to be able to reproduce the HC numbers from Enterobase by using your tool with the file "[profiles.list.gz](https://enterobase.warwick.ac.uk/schemes/Salmonella.cgMLSTv2/profiles.list.gz)". Do you think that it's possible and that I proceed the right way?

Best regards,

**Comment by Bio-finder** [comment]
Changing [n] to [str(n)] on line 135 fixed the issue.

In addition to that I spotted a more annoying mistake which caused the name of the sequence types to be mixed during the clustering so I post also here the solution: you need to change in line 36 `names = mat.T[0]` by `names = mat.T[0].deepcopy()` or your index will be mixed during the reordering of mat in the code.

**Comment by a-damC** [comment]
Thanks @Bio-finder 
I manually changed this in the version I downloaded via conda.
This seems to have worked for me.

**Comment by eam12** [comment]
@a-damC What version of pHierCC did you download via Conda? It seems that the most up to date version currently available via Conda (v.1.24) only has 126 lines. I think the version you and @Bio-finder were editing was 1.26 or 1.27?

**Comment by a-damC** [comment]
@eam12 I can't remember but I have started to use ReporTree for clustering. It's currently well maintained and an all encompassing set of code that includes single linkage clustering. https://github.com/insapathogenomics/ReporTree

**Comment by eam12** [comment]
@a-damC Many thanks for the recommendation! ReportTree looks like a really nice alternative.
